(function(c){c(window.jQuery,window,document)})(function(c,m,q){c.widget("selectBox.selectBoxIt",{VERSION:"3.2.0",options:{showEffect:"none",showEffectOptions:{},showEffectSpeed:"medium",hideEffect:"none",hideEffectOptions:{},hideEffectSpeed:"medium",showFirstOption:!0,defaultText:"",defaultIcon:"",downArrowIcon:"",theme:"default",keydownOpen:!0,isMobile:function(){return/iPhone|iPod|iPad|Android|BlackBerry|Opera Mini|IEMobile/.test(navigator.userAgent||navigator.vendor||m.opera)},"native":!1,aggressiveChange:!1,
selectWhenHidden:!0,viewport:c(m),similarSearch:!1,copyAttributes:["title","rel"],copyClasses:"button",nativeMousedown:!1,customShowHideEvent:!1},getThemes:function(){var a=c(this.element).attr("data-theme")||"c";return{bootstrap:{focus:"active",hover:"",disabled:"disabled",arrow:"caret",button:"btn",list:"dropdown-menu",container:"bootstrap",open:"open"},jqueryui:{focus:"ui-state-focus",hover:"ui-state-hover",disabled:"ui-state-disabled",arrow:"ui-icon ui-icon-triangle-1-s",button:"ui-widget ui-state-default",
list:"ui-widget ui-widget-content",container:"jqueryui",open:"selectboxit-open"},jquerymobile:{focus:"ui-btn-down-"+a,hover:"ui-btn-hover-"+a,disabled:"ui-disabled",arrow:"ui-icon ui-icon-arrow-d ui-icon-shadow",button:"ui-btn ui-btn-icon-right ui-btn-corner-all ui-shadow ui-btn-up-"+a,list:"ui-btn ui-btn-icon-right ui-btn-corner-all ui-shadow ui-btn-up-"+a,container:"jquerymobile",open:"selectboxit-open"},"default":{focus:"selectboxit-focus",hover:"selectboxit-hover",disabled:"selectboxit-disabled",
arrow:"selectboxit-default-arrow",button:"selectboxit-btn",list:"selectboxit-list",container:"selectboxit-container",open:"selectboxit-open"}}},_create:function(){if(this.element.is("select"))return this.originalElem=this.element[0],this.selectBox=this.element,this.selectItems=this.element.find("option"),this.firstSelectItem=this.selectItems.slice(0,1),this.documentHeight=c(q).height(),this.theme=this.getThemes()[this.options.theme]||this.getThemes()["default"],this.currentFocus=0,this.blur=!0,this.textArray=
[],this.currentIndex=0,this.currentText="",this.flipped=!1,this._createDropdownButton()._createUnorderedList()._copyAttributes()._replaceSelectBox()._addClasses(this.theme)._eventHandlers(),this.originalElem.disabled&&this.disable&&this.disable(),this._ariaAccessibility&&this._ariaAccessibility(),this._mobile&&this._mobile(),this.options["native"]&&this._applyNativeSelect(),this.triggerEvent("create"),this},_createDropdownButton:function(){var a=this.originalElem.id||"",b=this.options.copyClasses,
d=this.selectBox.attr("class");this.dropdownText=c("<span/>",{id:a&&a+"SelectBoxItText","class":"selectboxit-text",unselectable:"on",text:this.firstSelectItem.text()}).attr("data-val",this.originalElem.value);this.dropdownImageContainer=c("<span/>",{"class":"selectboxit-option-icon-container"});this.dropdownImage=c("<i/>",{id:a&&a+"SelectBoxItDefaultIcon","class":"selectboxit-default-icon",unselectable:"on"});this.dropdown=c("<span/>",{id:a&&a+"SelectBoxIt","class":"selectboxit "+("button"===b?d:
""),name:this.originalElem.name,tabindex:this.selectBox.attr("tabindex")||"0",unselectable:"on"}).append(this.dropdownImageContainer.append(this.dropdownImage)).append(this.dropdownText);this.dropdownContainer=c("<span/>",{id:a&&a+"SelectBoxItContainer","class":"selectboxit-container "+("container"===b?d:"")}).append(this.dropdown);return this},_createUnorderedList:function(){var a=this,b,d,f,p,g,e,k,h="",j=a.originalElem.id||"",j=c("<ul/>",{id:j&&j+"SelectBoxItOptions","class":"selectboxit-options",
tabindex:-1}),n;a.options.showFirstOption||(a.selectItems=a.selectBox.find("option").slice(1));a.selectItems.each(function(j){f=d="";b=c(this).prop("disabled");p=c(this).data("icon")||"";e=(g=c(this).data("iconurl")||"")?"selectboxit-option-icon-url":"";k=g?"style=\"background-image:url('"+g+"');\"":"";n=c(this).text();c(this).parent().is("optgroup")&&(d="selectboxit-optgroup-option",0===c(this).index()&&(f='<span class="selectboxit-optgroup-header" data-disabled="true">'+c(this).parent().first().attr("label")+
"</span>"));h+=f+'<li id="'+j+'" data-val="'+a.htmlEscape(this.value)+'" data-disabled="'+b+'" class="'+d+" selectboxit-option "+(c(this).attr("class")||"")+'"><a class="selectboxit-option-anchor"><span class="selectboxit-option-icon-container"><i class="selectboxit-option-icon '+p+" "+(e||a.theme.container)+'"'+k+"></i></span>"+a.htmlEscape(n)+"</a></li>";a.textArray[j]=b?"":n;this.selected&&(a.dropdownText.text(n),a.currentFocus=j)});if((a.options.defaultText||a.selectBox.data("text"))&&!a.selectBox.find("option[selected]").length){var m=
a.options.defaultText||a.selectBox.data("text");a.dropdownText.text(m);a.options.defaultText=m}j.append(h);a.list=j;a.dropdownContainer.append(a.list);a.listItems=a.list.find("li");a.listItems.first().addClass("selectboxit-option-first");a.listItems.last().addClass("selectboxit-option-last");a.list.find("li[data-disabled='true']").not(".optgroupHeader").addClass(a.theme.disabled);a.dropdownImage.addClass(a.selectBox.data("icon")||a.options.defaultIcon||a.listItems.eq(a.currentFocus).find("i").attr("class"));
a.dropdownImage.attr("style",a.listItems.eq(a.currentFocus).find("i").attr("style"));return a},_replaceSelectBox:function(){var a=this.originalElem.id||"";this.selectBox.css("display","none").after(this.dropdownContainer);this.dropdown.height();this.downArrow=c("<i/>",{id:a&&a+"SelectBoxItArrow","class":"selectboxit-arrow",unselectable:"on"});this.downArrowContainer=c("<span/>",{id:a&&a+"SelectBoxItArrowContainer","class":"selectboxit-arrow-container",unselectable:"on"}).append(this.downArrow);this.dropdown.append(this.downArrowContainer);
this.listItems.removeClass("selectboxit-selected").eq(this.currentFocus).addClass("selectboxit-selected");this.dropdownImageContainer.width()||this.dropdownImageContainer.remove();this.dropdownText.css({"max-width":this.dropdownContainer.width()-(this.downArrowContainer.outerWidth(!0)+this.dropdownImage.outerWidth(!0))});return this},_scrollToView:function(a){var b=this.listItems.eq(this.currentFocus),d=this.list.scrollTop(),f=b.height(),b=b.position().top,c=Math.abs(b),g=this.list.height();"search"===
a?g-b<f?this.list.scrollTop(d+(b-(g-f))):-1>b&&this.list.scrollTop(b-f):"up"===a?-1>b&&this.list.scrollTop(d-c):"down"===a&&g-b<f&&this.list.scrollTop(d+(c-g+f));return this},_callbackSupport:function(a){c.isFunction(a)&&a.call(this,this.dropdown);return this},open:function(a){var b=this,d=b.options.showEffect,f=b.options.showEffectSpeed,c=b.options.showEffectOptions,g=b.options["native"],e=b.options.isMobile();if(!b.listItems.length)return b;!g&&!e&&!this.list.is(":visible")&&(b.triggerEvent("open"),
b._dynamicPositioning&&b._dynamicPositioning(),"none"===d?b.list.show():"show"===d?b.list.show(f):"slideDown"===d?b.list.slideDown(f):"fadeIn"===d?b.list.fadeIn(f):b.list.show(d,c,f),b.list.promise().done(function(){b._scrollToView("search")}));b._callbackSupport(a);return b},close:function(a){var b=this.options.hideEffect,d=this.options.hideEffectSpeed,f=this.options.hideEffectOptions,c=this.options["native"],g=this.options.isMobile();!c&&!g&&this.list.is(":visible")&&(this.triggerEvent("close"),
"none"===b?this.list.hide():"hide"===b?this.list.hide(d):"slideUp"===b?this.list.slideUp(d):"fadeOut"===b?this.list.fadeOut(d):this.list.hide(b,f,d));this._callbackSupport(a);return this},toggle:function(){var a=this.list.is(":visible");a?this.close():a||this.open()},_keyMappings:{38:"up",40:"down",13:"enter",8:"backspace",9:"tab",32:"space",27:"esc"},_keydownMethods:function(){var a=this,b=a.list.is(":visible")||!a.options.keydownOpen;return{down:function(){a.moveDown&&b&&a.moveDown()},up:function(){a.moveUp&&
b&&a.moveUp()},enter:function(){var b=a.list.find("li."+a.focusClass);b.length||(b=a.listItems.first());a._update(b);a.list.is(":visible")&&a.close();a.triggerEvent("enter")},tab:function(){a.triggerEvent("tab-blur")},backspace:function(){a.triggerEvent("backspace")},esc:function(){a.close()}}},_eventHandlers:function(){var a=this,b=a.options.nativeMousedown,d=a.options.customShowHideEvent;this.dropdown.bind({"click.selectBoxIt":function(){a.dropdown.trigger("focus",!0);a.originalElem.disabled||(a.triggerEvent("click"),
!b&&!d&&a.toggle())},"mousedown.selectBoxIt":function(){c(this).data("mdown",!0);a.triggerEvent("mousedown");b&&!d&&a.toggle()},"mouseup.selectBoxIt":function(){a.triggerEvent("mouseup")},"blur.selectBoxIt":function(){a.blur&&(a.triggerEvent("blur"),a.list.is(":visible")&&a.close())},"focus.selectBoxIt":function(b,d){var g=c(this).data("mdown");c(this).removeData("mdown");!g&&!d&&setTimeout(function(){a.triggerEvent("tab-focus")},0);d||a.triggerEvent("focus")},"keydown.selectBoxIt":function(b){var d=
a._keyMappings[b.keyCode],c=a._keydownMethods()[d];c&&(c(),a.options.keydownOpen&&("up"===d||"down"===d)&&a.open());c&&"tab"!==d&&b.preventDefault()},"keypress.selectBoxIt":function(b){var d=b.charCode||b.keyCode,c=String.fromCharCode(d);a.search&&a.search(c,!0,!0);32===d&&b.preventDefault()},"mouseenter.selectBoxIt":function(){a.triggerEvent("mouseenter")},"mouseleave.selectBoxIt":function(){a.triggerEvent("mouseleave")}});a.list.bind({"mouseover.selectBoxIt":function(){a.blur=!1},"mouseout.selectBoxIt":function(){a.blur=
!0},"focusin.selectBoxIt":function(){a.dropdown.trigger("focus",!0)}}).delegate("li","click.selectBoxIt",function(){a._update(c(this));a.triggerEvent("option-click");"false"===c(this).attr("data-disabled")&&a.close()}).delegate("li","focusin.selectBoxIt",function(){a.listItems.not(c(this)).removeAttr("data-active");c(this).attr("data-active","");var b=a.list.is(":hidden");(a.options.searchWhenHidden&&b||a.options.aggressiveChange||b&&a.options.selectWhenHidden)&&a._update(c(this))}).delegate("li",
"mouseup.selectBoxIt",function(){b&&!d&&(a._update(c(this)),a.triggerEvent("option-mouseup"),"false"===c(this).attr("data-disabled")&&a.close())});a.selectBox.bind({"change.selectBoxIt, internal-change.selectBoxIt":function(b,d){var c;d||(c=a.list.find('li[data-val="'+a.originalElem.value+'"]'),c.length&&(a.listItems.eq(a.currentFocus).removeClass(a.focusClass),a.currentFocus=+c.attr("id")));c=a.listItems.eq(a.currentFocus);a.dropdownText.text(c.find("a").text()).attr("data-val",a.originalElem.value);
c.find("i").attr("class")&&(a.dropdownImage.attr("class",c.find("i").attr("class")).addClass("selectboxit-default-icon"),a.dropdownImage.attr("style",c.find("i").attr("style")));a.triggerEvent("changed")},"disable.selectBoxIt":function(){a.dropdown.addClass(a.theme.disabled)},"enable.selectBoxIt":function(){a.dropdown.removeClass(a.theme.disabled)}});return a},_update:function(a){"false"===a.attr("data-disabled")&&(this.options.defaultText&&this.dropdownText.text()===this.options.defaultText&&this.selectBox.val()===
a.attr("data-val")?this.dropdownText.text(this.listItems.eq(this.currentFocus).text()).trigger("internal-change"):(this.selectBox.val(a.attr("data-val")),this.currentFocus=+a.attr("id"),this.originalElem.value!==this.dropdownText.attr("data-val")&&this.triggerEvent("change")))},_addClasses:function(a){var b=this,d=a.focus,f=a.hover,e=a.button,g=a.list,l=a.arrow,k=a.container,h=a.open;b.focusClass=d;b.openClass=h;b.selectedClass="selectboxit-selected";b.downArrow.addClass(b.selectBox.data("downarrow")||
b.options.downArrowIcon||l);b.dropdownContainer.addClass(k);b.dropdown.addClass(e);b.list.addClass(g);b.listItems.bind({"focusin.selectBoxIt":function(){c(this).addClass(d)},"blur.selectBoxIt":function(){c(this).removeClass(d)}});b.selectBox.bind({"open.selectBoxIt":function(){var a=b.list.find("li[data-val='"+b.dropdownText.attr("data-val")+"']");a.length||(a=0===b.currentFocus&&!b.options.showFirstOption&&b.listItems.eq(0).hasClass(b.theme.disabled)?b.listItems.not("[data-disabled=true]").first():
b.listItems.first());b.currentFocus=+a.attr("id");a=b.listItems.eq(b.currentFocus);b.dropdown.addClass(h);b.dropdown.removeClass(f).addClass(d);b.listItems.removeClass(b.selectedClass);b.listItems.removeAttr("data-active").not(a).removeClass(d);a.addClass(d).addClass(b.selectedClass)},"close.selectBoxIt":function(){b.dropdown.removeClass(h)},"blur.selectBoxIt":function(){b.dropdown.removeClass(d)},"mouseenter.selectBoxIt":function(){b.dropdown.addClass(f)},"mouseleave.selectBoxIt":function(){b.dropdown.removeClass(f)}});
b.listItems.bind({"mouseenter.selectBoxIt":function(){"false"===c(this).attr("data-disabled")&&(b.listItems.removeAttr("data-active"),c(this).addClass(d).attr("data-active",""),b.listItems.not(c(this)).removeClass(d),c(this).addClass(d),b.currentFocus=+c(this).attr("id"))},"mouseleave.selectBoxIt":function(){"false"===c(this).attr("data-disabled")&&(b.listItems.not(c(this)).removeClass(d).removeAttr("data-active"),c(this).addClass(d),b.currentFocus=+c(this).attr("id"))}});return b},refresh:function(a){this._destroySelectBoxIt&&
(this._destroySelectBoxIt()._create(!0)._callbackSupport(a),this.triggerEvent("refresh"));return this},htmlEscape:function(a){return String(a).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;")},triggerEvent:function(a){this.selectBox.trigger(a,{elem:this.selectBox.eq(this.options.showFirstOption?this.currentFocus:0<=this.currentFocus-1?this.currentFocus:0),"dropdown-elem":this.listItems.eq(this.currentFocus)});return this},_copyAttributes:function(){this._addSelectBoxAttributes&&
this._addSelectBoxAttributes();return this}});var e=c.selectBox.selectBoxIt.prototype;e.disable=function(a){this.options.disabled||(this.close(),this.selectBox.attr("disabled","disabled"),this.dropdown.removeAttr("tabindex").addClass("selectboxit-disabled"),c.Widget.prototype.disable.call(this),this.triggerEvent("disable"));this._callbackSupport(a);return this};e.disableOption=function(a,b){var d,c;"number"===(typeof a).toLowerCase()&&(this.close(),d=this.selectBox.find("option").eq(a),this.triggerEvent("disable-option"),
d.attr("disabled","disabled"),this.listItems.eq(a).attr("data-disabled","true").addClass(this.theme.disabled),this.currentFocus===a&&(d=this.listItems.eq(this.currentFocus).nextAll("li").not("[data-disabled='true']").first().length,c=this.listItems.eq(this.currentFocus).prevAll("li").not("[data-disabled='true']").first().length,d?this.moveDown():c?this.moveUp():this.disable()));this._callbackSupport(b);return this};e._isDisabled=function(){this.originalElem.disabled&&this.disable();return this};e._dynamicPositioning=
function(){var a=this.dropdown.offset().top,b=this.list.data("max-height")||this.list.outerHeight(),d=this.dropdown.outerHeight(),f=this.options.viewport,e=f.height(),f=c.isWindow(f.get(0))?f.scrollTop():f.offset().top,g=!(a+d+b<=e+f);this.list.data("max-height")||this.list.data("max-height",this.list.outerHeight());g?this.dropdown.offset().top-f>=b?(this.list.css("max-height",b),this.list.css("top",this.dropdown.position().top-this.list.outerHeight())):(a=Math.abs(a+d+b-(e+f)),e=Math.abs(this.dropdown.offset().top-
f-b),a<e?(this.list.css("max-height",b-a-d/2),this.list.css("top","auto")):(this.list.css("max-height",b-e-d/2),this.list.css("top",this.dropdown.position().top-this.list.outerHeight()))):(this.list.css("max-height",b),this.list.css("top","auto"));return this};e.enable=function(a){this.options.disabled&&(this.triggerEvent("enable"),this.selectBox.removeAttr("disabled"),this.dropdown.attr("tabindex",0).removeClass(this.disabledClasses),c.Widget.prototype.enable.call(this),this._callbackSupport(a));
return this};e.enableOption=function(a,b){var d;"number"===(typeof a).toLowerCase()&&(d=this.selectBox.find("option").eq(a),this.triggerEvent("enable-option"),d.removeAttr("disabled"),this.listItems.eq(a).attr("data-disabled","false").removeClass(this.disabledClasses));this._callbackSupport(b);return this};e.moveDown=function(a){this.currentFocus+=1;var b="true"===this.listItems.eq(this.currentFocus).attr("data-disabled")?!0:!1,d=this.listItems.eq(this.currentFocus).nextAll("li").not("[data-disabled='true']").first().length;
if(this.currentFocus===this.listItems.length)this.currentFocus-=1;else{if(b&&d){this.listItems.eq(this.currentFocus-1).blur();this.moveDown();return}b&&!d?this.currentFocus-=1:(this.listItems.eq(this.currentFocus-1).blur().end().eq(this.currentFocus).focusin(),this._scrollToView("down"),this.triggerEvent("moveDown"))}this._callbackSupport(a);return this};e.moveUp=function(a){this.currentFocus-=1;var b="true"===this.listItems.eq(this.currentFocus).attr("data-disabled")?!0:!1,d=this.listItems.eq(this.currentFocus).prevAll("li").not("[data-disabled='true']").first().length;
if(-1===this.currentFocus)this.currentFocus+=1;else{if(b&&d){this.listItems.eq(this.currentFocus+1).blur();this.moveUp();return}b&&!d?this.currentFocus+=1:(this.listItems.eq(this.currentFocus+1).blur().end().eq(this.currentFocus).focusin(),this._scrollToView("up"),this.triggerEvent("moveUp"))}this._callbackSupport(a);return this};e._setCurrentSearchOption=function(a){if((this.options.aggressiveChange||this.options.selectWhenHidden||this.listItems.eq(a).is(":visible"))&&!0!==this.listItems.eq(a).data("disabled"))this.listItems.eq(this.currentFocus).blur(),
this.currentFocus=this.currentIndex=a,this.listItems.eq(this.currentFocus).focusin(),this._scrollToView("search"),this.triggerEvent("search");return this};e._searchAlgorithm=function(a,b){var d=!1,c,e,g,l,k=this.textArray,h=this.currentText;c=a;for(g=k.length;c<g;c+=1){l=k[c];for(e=0;e<g;e+=1)-1!==k[e].search(b)&&(d=!0,e=g);d||(h=this.currentText=this.currentText.charAt(this.currentText.length-1).replace(/[|()\[{.+*?$\\]/g,"\\$0"));b=RegExp(h,"gi");if(3>h.length){if(b=RegExp(h.charAt(0),"gi"),-1!==
l.charAt(0).search(b)){this._setCurrentSearchOption(c);if(l.substring(0,h.length).toLowerCase()!==h.toLowerCase()||this.options.similarSearch)this.currentIndex+=1;return!1}}else if(-1!==l.search(b))return this._setCurrentSearchOption(c),!1;if(l.toLowerCase()===this.currentText.toLowerCase())return this._setCurrentSearchOption(c),this.currentText="",!1}return!0};e.search=function(a,b,c){this.currentText=c?this.currentText+a.replace(/[|()\[{.+*?$\\]/g,"\\$0"):a.replace(/[|()\[{.+*?$\\]/g,"\\$0");this._searchAlgorithm(this.currentIndex,
RegExp(this.currentText,"gi"))&&this._searchAlgorithm(0,this.currentText);this._callbackSupport(b);return this};e.selectOption=function(a,b){"number"===(typeof a).toLowerCase()?this.selectBox.val(this.selectBox.find("option").eq(a).val()).change():"string"===(typeof a).toLowerCase()&&this.selectBox.val(a).change();this._callbackSupport(b);return this};e.setOption=function(a,b,d){var e=this.listItems.eq(0);"showFirstOption"===a&&!b?e.hide():"showFirstOption"===a&&b?e.show():"defaultIcon"===a&&b?this.dropdownImage.attr("class",
b+" selectboxit-arrow"):"downArrowIcon"===a&&b?this.downArrow.attr("class",b+" selectboxit-arrow"):"defaultText"===a&&this.dropdownText.text(b);c.Widget.prototype._setOption.apply(this,arguments);this._callbackSupport(d);return this}});
